### ISSUE TITLE
Epic: Release current main branch as version 0.6

### ISSUE THREAD

**Issue by CSchoel** [CSchoel/nolds#26]
## Sub-Issues:

- [x] #29
- [x] #30
- [x] #31
- [x] #25
- [x] #33
- [x] #17

**Comment by CSchoel** [comment]
There were a few things that still needed an update after I haven't done a release in such a long while:

- [x] Updated the Sphinx documentation with the new features.
- [x] Re-activated or deleted all service accounts for the badges shown in the README.
- [x] Fixed CI tests.
- [x] Modernized configuration for readthedocs.io.

**Comment by CSchoel** [comment]
[Nolds 0.6.0](https://github.com/CSchoel/nolds/releases/tag/0.6.0) is released and installable. Everything seems to be going fine! :tada: 

The coast is finally clear to modernize the codebase. :smile:
