### ISSUE TITLE
Epic: Introduce breaking changes and improvements required for 1.0

### ISSUE THREAD

**Issue by CSchoel** [CSchoel/nolds#28]
## Sub-issues

- [ ] Go through TODOs in the code.
- [ ] Reduce the size of unit tests so that they run in less than three minutes.
- [ ] Make unit tests fully deterministic.
- [ ] Adjust default values such that the version of the algorithm run with default settings is as close to the corresponding paper as possible.
