### ISSUE TITLE
complete Lorenz example

### ISSUE THREAD

**Issue by CSchoel** [CSchoel/nolds#29]
The code calculating metrics for the Lorenz system of ODEs in `examples.py` already contains examples for all major nolds algorithms. However, I want to double-check if all the results make sense or if there is still something to tweak with the parameters. For example, #25 has shown that some changes might be required for `corr_dim`.

## Todo

- [x] Check if all values are in expected range.
- [x] Try to solve unexpected deviations with more fine-grained parameters.
- [x] Experiment with skipping the first X datapoints.
- [x] Set `lag` for `corr_dim`.
- [x] Set `tau` parameter for Lorenz system closer to values in Grassberger Procaccia 1983.
