### ISSUE TITLE
use Lorenz example for unit tests

### ISSUE THREAD

**Issue by CSchoel** [CSchoel/nolds#30]
Since the example using the Lorenz system in `examples.py` has reference values for all major nolds algorithms, it would be great to use those in the unit tests.

## To-Do

- [x] Add Lorenz test for `sampen`.
- [x] Add Lorenz test for `corr_dim`.
- [x] Add Lorenz test for `lyap_r`.
- [x] Add Lorenz test for `lyap_e`.
- [x] Add Lorenz test for `hurst_rs`.
- [x] Add Lorenz test for `dfa`.

**Comment by CSchoel** [comment]
This is done, save for a bit of documentation.
